import React, {useEffect, useState, useCallback} from 'react'
import {createRoot} from 'react-dom/client'
import * as Dialog from '@radix-ui/react-dialog'
import {Activity, ArrowDownLeft, ArrowRight, Check, CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, ClipboardCheck, Database, FileText, HeartPulse, LayoutDashboard, LoaderCircle, LockKeyhole, LogOut, Menu, Mic, MoreHorizontal, Phone, Plus, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, Trash2, Users, X, Pencil, AlertCircle, Globe, Mail, MapPin, CalendarDays} from 'lucide-react'
import {api, API_BASE, ApiError, Patient, Call, Stats, Config, formatPhone, shortDate, initials} from './api'
import './styles.css'

type Page='overview'|'patients'|'calls'|'system'
const navigation=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'patients',label:'Patients',icon:Users},{id:'calls',label:'Call history',icon:Phone},{id:'system',label:'System status',icon:Settings2}] as const
const labels:Record<string,string>={first_name:'First name',last_name:'Last name',date_of_birth:'Date of birth',sex:'Sex',phone_number:'Phone number',email:'Email address',address_line_1:'Street address',address_line_2:'Apartment / suite',city:'City',state:'State',zip_code:'ZIP code',insurance_provider:'Insurance provider',insurance_member_id:'Member ID',preferred_language:'Preferred language',emergency_contact_name:'Emergency contact',emergency_contact_phone:'Emergency phone'}
const groups=[{name:'Demographics',fields:['first_name','last_name','date_of_birth','sex']},{name:'Contact & address',fields:['phone_number','email','address_line_1','address_line_2','city','state','zip_code']},{name:'Insurance & preferences',fields:['insurance_provider','insurance_member_id','preferred_language']},{name:'Emergency contact',fields:['emergency_contact_name','emergency_contact_phone']}]
const required=new Set(['first_name','last_name','date_of_birth','sex','phone_number','address_line_1','city','state','zip_code','preferred_language'])

function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:React.ReactNode;wide?:boolean}){return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className={`modal ${wide?'wide':''}`}><div className="modal-head"><div><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description||'Manage this record in your patient workspace.'}</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="Close dialog"><X size={20}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
function Empty({type,onAdd}:{type:'patients'|'calls';onAdd?:()=>void}){return <div className="empty"><span className="empty-icon">{type==='patients'?<Users/>:<Phone/>}</span><h3>{type==='patients'?'Your patient workspace starts here':'Ready for your first conversation'}</h3><p>{type==='patients'?'Confirmed voice registrations appear here automatically. You can also add a fictional patient to test the workflow.':'Call your intake number to register a fictional patient. Completed calls will appear here.'}</p>{onAdd&&<button className="button secondary" onClick={onAdd}><Plus size={16}/> Add patient</button>}</div>}
function PatientForm({patient,onClose,onSaved,accessKey}:{patient:Patient|null;onClose:()=>void;onSaved:()=>void;accessKey:string}){
 const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(Object.keys(labels).map(k=>[k,String(patient?.[k as keyof Patient]??(k==='preferred_language'?'English':''))])))
 const [errors,setErrors]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setErrors({});setMessage('');try{
  const body=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,required.has(k)?v:(v||null)]))
  await api(`/patients${patient?'/'+patient.patient_id:''}`,accessKey,{method:patient?'PUT':'POST',body:JSON.stringify(body)});onSaved()
 }catch(e){const err=e as ApiError;setMessage(err.message);setErrors(Object.fromEntries((err.details||[]).map(d=>[d.field.replace(/^body\./,''),d.message])))}finally{setBusy(false)}}
 return <Modal open onClose={onClose} title={patient?'Edit patient':'New patient'} description="Use fictional information only. Required fields are marked with an asterisk." wide><form onSubmit={save}><div className="modal-body form-body">{groups.map(group=><section className="form-section" key={group.name}><h3>{group.name}</h3><div className="form-grid">{group.fields.map(field=><label key={field} className={field==='address_line_1'?'span-two':''}>{labels[field]}{required.has(field)&&<span className="required"> *</span>}{field==='sex'?<select value={values[field]} required onChange={e=>{const value=e.target.value;setValues(previous=>({...previous,[field]:value}))}}><option value="">Select sex</option>{['Male','Female','Other','Decline to Answer'].map(s=><option key={s}>{s}</option>)}</select>:field==='state'?<select required value={values[field]} onChange={e=>{const value=e.target.value;setValues(previous=>({...previous,[field]:value}))}}><option value="">Select state</option>{'AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY DC AS GU MP PR VI'.split(' ').map(s=><option key={s}>{s}</option>)}</select>:<input required={required.has(field)} type={field==='date_of_birth'?'date':field==='email'?'email':field.includes('phone')?'tel':'text'} max={field==='date_of_birth'?new Date().toISOString().slice(0,10):undefined} maxLength={field==='first_name'||field==='last_name'?50:field==='zip_code'?10:200} value={values[field]} onChange={e=>{const value=e.target.value;setValues(previous=>({...previous,[field]:value}))}} aria-invalid={!!errors[field]}/>} {errors[field]&&<small className="field-error">{errors[field]}</small>}</label>)}</div></section>)}</div><div className="modal-footer">{message&&<p role="alert" className="error-text">{message}</p>}<button className="button secondary" type="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {busy?'Saving…':patient?'Save changes':'Create patient'}</button></div></form></Modal>
}
function PatientDetails({patient,onClose,onEdit,onDelete}:{patient:Patient;onClose:()=>void;onEdit:()=>void;onDelete:()=>void}){return <Modal open onClose={onClose} title="Patient record" wide><div className="modal-body"><div className="profile"><div className="avatar large">{initials(patient)}</div><div><h2>{patient.first_name} {patient.last_name}</h2><p>{formatPhone(patient.phone_number)} <span className="dot-separator">·</span> {patient.city}, {patient.state}</p></div><span className="badge">Active</span></div>{groups.map(g=><section className="detail-section" key={g.name}><h3>{g.name}</h3><dl>{g.fields.map(f=><div key={f}><dt>{labels[f]}</dt><dd>{f==='date_of_birth'?shortDate(patient.date_of_birth):String(patient[f as keyof Patient]||'Not provided')}</dd></div>)}</dl></section>)}<section className="detail-section metadata"><h3>Record information</h3><p>ID <code>{patient.patient_id}</code></p><p>Created {shortDate(patient.created_at)} · Updated {shortDate(patient.updated_at)}</p></section></div><div className="modal-footer"><button className="button danger subtle" onClick={onDelete}><Trash2 size={16}/>Archive patient</button><div className="spacer"/><button className="button primary" onClick={onEdit}><Pencil size={16}/>Edit patient</button></div></Modal>}
function App(){
 const [page,setPage]=useState<Page>('overview'),[config,setConfig]=useState<Config|null>(null),[key,setKey]=useState(''),[keyInput,setKeyInput]=useState(''),[authorized,setAuthorized]=useState(false),[menu,setMenu]=useState(false)
 const [patients,setPatients]=useState<Patient[]>([]),[calls,setCalls]=useState<Call[]>([]),[stats,setStats]=useState<Stats|null>(null),[total,setTotal]=useState(0),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[filtersOpen,setFiltersOpen]=useState(false),[lastName,setLastName]=useState(''),[birthDate,setBirthDate]=useState('')
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[healthy,setHealthy]=useState(false),[toast,setToast]=useState(''),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState<Patient|null>(null),[form,setForm]=useState<'new'|'edit'|null>(null),[deleting,setDeleting]=useState(false),[busy,setBusy]=useState(false),[callDetail,setCallDetail]=useState<Call|null>(null),[testOpen,setTestOpen]=useState(false),[lastUpdated,setLastUpdated]=useState<Date|null>(null)
 useEffect(()=>{api<Config>('/config').then(r=>{setConfig(r.data);if(!r.data.auth_required)setAuthorized(true)}).catch(e=>{setError(e.message);setLoading(false)})},[refresh])
 useEffect(()=>{const id=setTimeout(()=>{setSearch(query);setOffset(0)},300);return()=>clearTimeout(id)},[query])
 const load=useCallback(async()=>{if(!authorized)return;setLoading(true);setError('');try{
  const [p,c,s,h]=await Promise.all([api<Patient[]>(`/patients?limit=10&offset=${offset}&q=${encodeURIComponent(search)}${lastName?`&last_name=${encodeURIComponent(lastName)}`:''}${birthDate?`&date_of_birth=${birthDate}`:''}`,key),api<Call[]>('/calls?limit=100',key),api<Stats>('/stats',key),api('/health')]);setPatients(p.data);setTotal(p.meta?.total||0);setCalls(c.data);setStats(s.data);setHealthy(!!h.data);setLastUpdated(new Date())
 }catch(e){const err=e as ApiError;setError(err.message);setHealthy(false);if(err.status===401)setAuthorized(false)}finally{setLoading(false)}},[authorized,key,offset,search,lastName,birthDate])
 useEffect(()=>{void load()},[load,refresh])
 useEffect(()=>{if(!authorized)return;const id=setInterval(()=>setRefresh(r=>r+1),30000);return()=>clearInterval(id)},[authorized])
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t)}},[toast])
 function navigate(p:Page){setPage(p);setMenu(false);setQuery('');setOffset(0);setLastName('');setBirthDate('')}
 function saved(){setForm(null);setSelected(null);setToast('Patient record saved successfully.');setRefresh(r=>r+1)}
 async function remove(){if(!selected)return;setBusy(true);try{await api('/patients/'+selected.patient_id,key,{method:'DELETE'});setDeleting(false);setSelected(null);setToast('Patient archived. The record is retained in storage.');setRefresh(r=>r+1)}catch(e){setToast((e as Error).message)}finally{setBusy(false)}}
 async function openCall(c:Call){try{const r=await api<Call>('/calls/'+c.call_id,key);setCallDetail(r.data)}catch(e){setToast((e as Error).message)}}
 const dateLabel=new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date())
 const patientTable=<div className="table-scroll"><table><thead><tr><th>Patient</th><th>Date of birth</th><th>Phone number</th><th>Location</th><th>Insurance</th><th>Registered</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{patients.map(p=><tr key={p.patient_id}><td><button className="patient-link" onClick={()=>setSelected(p)}><span className="avatar">{initials(p)}</span><span><strong>{p.first_name} {p.last_name}</strong><small>{p.sex}</small></span></button></td><td>{shortDate(p.date_of_birth)}</td><td className="tabular">{formatPhone(p.phone_number)}</td><td>{p.city}, {p.state}</td><td>{p.insurance_provider?<span className="insurance">{p.insurance_provider}</span>:<span className="muted">Not provided</span>}</td><td>{shortDate(p.created_at)}</td><td><button className="icon-button" aria-label={`Open ${p.first_name} ${p.last_name}`} onClick={()=>setSelected(p)}><ChevronRight size={18}/></button></td></tr>)}</tbody></table></div>
 return <div className="app-shell"><aside className={`sidebar ${menu?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('overview')}}><span className="brand-icon"><HeartPulse size={25}/></span><span>CareIntake<span className="brand-ai">AI</span><small>Voice Patient Registration</small></span></a><div className="workspace-pill"><span className="workspace-avatar">C</span><div>Care workspace<small>Assessment environment</small></div><ShieldCheck size={17}/></div><p className="nav-heading">WORKSPACE</p><nav>{navigation.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>navigate(n.id)}><n.icon size={19}/>{n.label}{n.id==='patients'&&stats&&<span className="nav-count">{stats.total_patients}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-note"><ShieldCheck size={19}/><h4>Made for demonstration</h4><p>Use fictional patient details. This workspace is not for real medical records.</p></div><a href={`${API_BASE}/docs`} target="_blank" rel="noreferrer" className="sidebar-link"><FileText size={17}/> API documentation <ArrowRight size={15}/></a><div className="user"><span className="user-avatar">SA</span><div>Salman’s workspace<small>Administrator</small></div>{config?.auth_required&&authorized&&<button className="icon-button" title="Lock workspace" onClick={()=>{setKey('');setAuthorized(false);setPatients([]);setCalls([]);setStats(null)}}><LogOut size={17}/></button>}</div></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={()=>setMenu(!menu)}><Menu size={21}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{navigation.find(n=>n.id===page)?.label}</strong></div><div className="topbar-right"><span className={`online ${healthy?'':'offline'}`}><i/>{healthy?'API & database online':'Checking connection'}</span><span className="topbar-divider"/><button className="icon-button" title="Testing guide" onClick={()=>setTestOpen(true)}><CircleHelp size={19}/></button><span className="top-avatar">SA</span></div></header><main>
 {!authorized&&config?.auth_required?<section className="login panel"><span className="empty-icon"><LockKeyhole/></span><div className="eyebrow">CAREINTAKE WORKSPACE</div><h1>Welcome back.</h1><p>Enter your reviewer access key to view patient records and call activity.</p><form onSubmit={e=>{e.preventDefault();setKey(keyInput);setAuthorized(true);setKeyInput('')}}><label>Reviewer access key<input type="password" value={keyInput} required autoComplete="off" onChange={e=>setKeyInput(e.target.value)}/></label>{error&&<p role="alert" className="error-text">{error}</p>}<button className="button primary">Unlock workspace <ArrowRight size={16}/></button></form><small>Demo environment · Fictional data only</small></section>:<>
 <div className="page-heading"><div><div className="eyebrow">{page==='overview'?'YOUR INTAKE, AT A GLANCE':page==='patients'?'PATIENT DIRECTORY':page==='calls'?'CONVERSATION ACTIVITY':'CONNECTED SERVICES'}</div><h1>{page==='overview'?'A little less admin. More care.':page==='patients'?'Patient records':page==='calls'?'Every conversation, connected.':'Your intake system'}</h1><p>{page==='overview'?'Keep a clear view of registrations, conversations, and the people behind them.':page==='patients'?'Find, review, and manage your registered patients.':page==='calls'?'Review voice intake outcomes and linked patient records.':'Check service health and find everything you need to test the workflow.'}</p></div><div className="heading-actions">{page==='overview'?<span className="date-label"><CalendarDays size={16}/>{dateLabel}</span>:<button className="button secondary" onClick={()=>setRefresh(r=>r+1)}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button>}{page!=='system'&&<button className="button primary" onClick={()=>setForm('new')}><Plus size={17}/>New patient</button>}</div></div>
 {error&&<div className="error-banner" role="alert"><AlertCircle size={20}/><div><strong>We couldn’t load the workspace.</strong><p>{error}</p></div><button className="button secondary" onClick={()=>setRefresh(r=>r+1)}>Try again</button></div>}
 {page==='overview'&&<><div className="stats-grid">{[{label:'Total patients',value:stats?.total_patients,icon:Users,note:'Active patient records'},{label:'Registered today',value:stats?.registered_today,icon:ClipboardCheck,note:'Since midnight UTC'},{label:'Total calls',value:stats?.total_calls,icon:Phone,note:'Recorded intake conversations'},{label:'Calls with a registration',value:stats?.registration_rate==null?'—':stats.registration_rate+'%',icon:Activity,note:stats?.total_calls?`${stats.registered_calls} of ${stats.total_calls} calls saved a patient`:'Available after the first call'}].map((s,i)=><div className="stat-card" key={s.label}><div className="stat-label">{s.label}<s.icon size={18}/></div><div className="stat-value">{s.value??(loading?'—':0)}{i===1&&!!stats?.registered_today&&<span className="stat-pill"><ArrowDownLeft size={13}/>New</span>}</div><small>{s.note}</small></div>)}</div><div className="voice-banner"><div className="voice-mark"><Mic size={27}/><span className="voice-rings"/></div><div className="voice-banner-copy"><div className="eyebrow">MEET YOUR INTAKE ASSISTANT</div><h2>A warm welcome, on every call.</h2><p>Riley gathers the details, confirms them with the caller, and creates a patient record.</p></div><div className="voice-banner-action">{config?.phone_number?<a className="phone-number" href={`tel:${config.phone_number}`}>{config.phone_number}</a>:<span className="phone-pending">Phone setup in progress</span>}<button onClick={()=>setTestOpen(true)}>Test the experience <ArrowRight size={16}/></button></div></div></>}
 {(page==='overview'||page==='patients')&&<section className="panel patients-panel"><div className="panel-heading"><div><h2>{page==='overview'?'Recent patients':'All patients'}<span className="count-chip">{total}</span></h2><p>{page==='overview'?'The latest registrations in your workspace.':'Confirmed registrations, available in one place.'}</p></div>{page==='overview'&&<button className="text-button" onClick={()=>navigate('patients')}>View all patients <ArrowRight size={16}/></button>}</div><div className="table-toolbar"><div className="search-field"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name or phone number…" aria-label="Search patients"/>{query&&<button className="icon-button" aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</div><button className="filter-button" onClick={()=>setFiltersOpen(v=>!v)} aria-expanded={filtersOpen}><Settings2 size={15}/>Filters{(lastName||birthDate)&&<i/>}</button><span className="active-filter"><span/>Active patients</span><button className="icon-button refresh-button" onClick={()=>setRefresh(r=>r+1)} aria-label="Refresh patients"><RefreshCw size={17} className={loading?'spin':''}/></button></div>{filtersOpen&&<div className="filter-row"><label>Exact last name<input value={lastName} onChange={e=>{setLastName(e.target.value);setOffset(0)}} placeholder="e.g. Bennet"/></label><label>Date of birth<input type="date" value={birthDate} onChange={e=>{setBirthDate(e.target.value);setOffset(0)}}/></label><button className="text-button" onClick={()=>{setLastName('');setBirthDate('');setOffset(0)}}>Clear filters</button></div>}{loading&&!patients.length?<div className="loading-state"><LoaderCircle className="spin"/>Loading patient records…</div>:patients.length?patientTable:search?<div className="empty"><Search/><h3>No matching patients</h3><p>Try a different name or phone number.</p><button className="text-button" onClick={()=>setQuery('')}>Clear search</button></div>:<Empty type="patients" onAdd={()=>setForm('new')}/>}<div className="table-footer"><span>{total?`${offset+1}–${Math.min(offset+10,total)} of ${total} patients`:'No patient records yet'}</span><div><button className="icon-button" disabled={offset===0||loading} aria-label="Previous page" onClick={()=>setOffset(Math.max(0,offset-10))}><ChevronLeft size={17}/></button><span>Page {Math.floor(offset/10)+1}</span><button className="icon-button" disabled={offset+10>=total||loading} aria-label="Next page" onClick={()=>setOffset(offset+10)}><ChevronRight size={17}/></button></div></div></section>}
 {(page==='overview'||page==='calls')&&<div className={page==='overview'?'lower-grid':''}><section className="panel"><div className="panel-heading"><div><h2>{page==='overview'?'Recent conversations':'Call history'}</h2><p>Every saved record starts with a confirmation.</p></div><span className="small-icon"><Phone size={18}/></span></div>{calls.length?<div className="call-list">{calls.slice(0,page==='overview'?3:100).map(c=><button key={c.call_id} className="call-item" onClick={()=>void openCall(c)}><span className="call-icon"><ArrowDownLeft size={20}/></span><span className="call-main"><strong>{formatPhone(c.caller_phone)}</strong><small>{shortDate(c.started_at)} · {new Date(c.started_at).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</small></span><span className={`badge ${c.patient_id?'':'neutral'}`}>{c.patient_id?'Registered':c.ended_at?'Not saved':'In progress'}</span><ChevronRight size={16}/></button>)}</div>:<Empty type="calls"/>}{page==='overview'&&calls.length>0&&<button className="panel-bottom-link" onClick={()=>navigate('calls')}>View call history <ArrowRight size={16}/></button>}</section>{page==='overview'&&<section className="panel workflow-panel"><div className="panel-heading"><div><h2>Thoughtful intake, by design</h2><p>A clear path from hello to saved.</p></div><ShieldCheck size={20}/></div><div className="workflow">{[{name:'Collect naturally',note:'Capture details at the caller’s pace.',icon:Mic},{name:'Confirm together',note:'Read back details and handle corrections.',icon:ClipboardCheck},{name:'Save with confidence',note:'Validated records, persisted securely.',icon:Database}].map((step,i)=><div className="workflow-step" key={step.name}><span><step.icon size={17}/></span><div><h4>{step.name}</h4><p>{step.note}</p></div><small>0{i+1}</small></div>)}</div></section>}</div>}
 {page==='system'&&<div className="system-grid"><section className="panel"><div className="panel-heading"><div><h2>Service health</h2><p>API and database are checked live.</p></div><Activity size={20}/></div><div className="service-list">{[{name:'REST API',value:healthy?'Connected':'Unavailable',icon:Globe,good:healthy},{name:'Persistent database',value:healthy?'Connected':'Unavailable',icon:Database,good:healthy},{name:'Vapi assistant',value:config?.assistant_configured?'Configured':'Pending setup',icon:Mic,good:config?.assistant_configured},{name:'U.S. intake number',value:config?.phone_number||'Pending provisioning',icon:Phone,good:!!config?.phone_number}].map(s=><div className="service" key={s.name}><s.icon size={20}/><strong>{s.name}</strong><span className={`badge ${s.good?'':'neutral'}`}>{s.value}</span></div>)}</div><div className="system-note"><AlertCircle size={16}/><p>“Configured” confirms saved settings. Complete a phone call to verify the entire voice pipeline.</p></div></section><section className="panel testing-panel"><span className="empty-icon"><ClipboardCheck/></span><h2>Take the full journey.</h2><p>Call Riley with fictional details, make a correction, confirm, and find the new record in Patients.</p><button className="button primary" onClick={()=>setTestOpen(true)}>Open testing guide <ArrowRight size={16}/></button><a className="text-button" href={`${API_BASE}/docs`} target="_blank" rel="noreferrer">Explore REST API <ArrowRight size={16}/></a></section></div>}
 <footer className="page-footer"><span><ShieldCheck size={14}/>Assessment demo · Fictional patient data only</span><span>{lastUpdated?`Last synced ${lastUpdated.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}`:'Awaiting connection'}<span className="footer-dot">·</span>CareIntake AI</span></footer></>}
 </main></div>{toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}<button className="icon-button" aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 {selected&&!form&&!deleting&&<PatientDetails patient={selected} onClose={()=>setSelected(null)} onEdit={()=>setForm('edit')} onDelete={()=>setDeleting(true)}/>}{form&&<PatientForm patient={form==='edit'?selected:null} accessKey={key} onClose={()=>setForm(null)} onSaved={saved}/>}
 {deleting&&<Modal open onClose={()=>setDeleting(false)} title="Archive this patient?" description="The patient will be removed from active views. Their stored record will be retained."><div className="modal-body"><p>{selected?.first_name} {selected?.last_name} will no longer appear in search results or the active patient directory.</p></div><div className="modal-footer"><button className="button secondary" onClick={()=>setDeleting(false)}>Keep patient</button><button className="button danger" disabled={busy} onClick={()=>void remove()}>{busy?'Archiving…':'Archive patient'}</button></div></Modal>}
 {callDetail&&<Modal open onClose={()=>setCallDetail(null)} title="Conversation details" description={callDetail.provider_call_id} wide><div className="modal-body"><div className="call-detail-meta"><span className="badge">{callDetail.status}</span><span>{shortDate(callDetail.started_at)}</span><span>{callDetail.ended_at?Math.max(0,Math.round((Date.parse(callDetail.ended_at)-Date.parse(callDetail.started_at))/1000))+' seconds':'In progress'}</span></div><h3>Call summary</h3><p className="call-summary">{callDetail.summary||'No summary received yet.'}</p>{callDetail.patient_id&&<button className="button secondary" onClick={async()=>{try{const p=await api<Patient>('/patients/'+callDetail.patient_id,key);setCallDetail(null);setSelected(p.data)}catch(e){setToast((e as Error).message)}}}>Open linked patient <ArrowRight size={16}/></button>}<h3 className="transcript-heading">Transcript</h3><pre className="transcript">{callDetail.transcript||'Transcript storage is disabled or no transcript was provided.'}</pre></div></Modal>}
 {testOpen&&<Modal open onClose={()=>setTestOpen(false)} title="Try a complete registration" description="Use the fictional details below to test the voice-to-record workflow."><div className="modal-body"><div className="test-number"><Phone/>{config?.phone_number?<a href={`tel:${config.phone_number}`}>{config.phone_number}</a>:<strong>Phone number pending configuration</strong>}</div><ol className="test-steps"><li><strong>Introduce yourself naturally.</strong><p>“I’m Morgan Bennett, born February 8, 1998. My phone is 732-555-0184.”</p></li><li><strong>Finish the required details.</strong><p>“Female. 27 Oak Street, Somerset, New Jersey, 08873.” Skip optional information if you like.</p></li><li><strong>Make a correction before approving.</strong><p>“Actually, my last name is Bennet, with one T.” The assistant should read back the corrected details.</p></li><li><strong>Explicitly confirm.</strong><p>Say “Yes, all of that is correct.” Wait for a successful save, then look for Morgan in Patients.</p></li><li><strong>Call back.</strong><p>Use the same phone, last name, and date of birth to verify that the previous record persists.</p></li></ol></div></Modal>}
 </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
